export const GET_DOGS = "GET_DOGS";
export const GET_DOGS_BY_NAME ="GET_DOGS_BY_NAME";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const GET_DOG_DETAIL = "GET_DOG_DETAIL";
export const ALPHABETICAL_ORDER ="ALPHABETICAL_ORDER";
export const WEIGHT_ORDER ="WEIGHT_ORDER";
export const CREATE_DOG ="CREATE_DOG";